#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "phpservermon"
name = "PHP Server Monitor"
description.en = "Script that checks whether your websites and servers are up and running"
description.fr = "Application pour vérifier que vos sites web et serveurs fonctionnent"

version = "v3.5.2~ynh1"

maintainers = ["Benoit"]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.phpservermonitor.org/"
code = "https://github.com/phpservermon/phpservermon/"
admindoc = "https://docs.phpservermonitor.org/en/latest/"
fund = "https://github.com/sponsors/TimZ99"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpservermon"

    [install.init_main_permission]
    help.en = "If the app is not public, only YunoHost users will have access to it"
    help.fr = "Si l'application n'est pas publique, seul les utilisateurs de YunoHost y auront accés"
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/phpservermon/phpservermon/archive/refs/tags/v3.5.2.tar.gz"
    sha256 = "1daab5ff8eb07726e805f551017dcb0311990b0bddb5a49e01e257c0bd6f5a4c"
    in_subdir = 2 # Yes, 2 levels

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "tarball"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "php7.4-fpm",
        "php7.4-curl",
        "php7.4-common",
        "php7.4-json",
        "php7.4-xml",
        "mariadb-server"
    ]

    [resources.database]
    type = "mysql"
