#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# Update Config file
#=================================================

if [ "$change_path" -eq 1 ]; then
    # Update config file
    ynh_replace --match="'PSM_BASE_URL', '.*'" --replace="'PSM_BASE_URL', '$path'" --file="$install_dir/config.php"
    #replace checksum
    ynh_delete_file_checksum "$install_dir/config.php"
    ynh_store_file_checksum "$install_dir/config.php"
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
